trial3<- read.table("household_power_consumption.txt",skip=1,sep=";")
names(trial3)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subtrial$Date<-as.Date(subtrial$Date,format="%d/%m/%y")
subtrial$Time<-strptime(subtrial$Time,format="%H:%M:%S")
subtrial[1:1440,"Time"] <- format(subtrial[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subtrial[1441:2880,"Time"] <- format(subtrial[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(subtrial$Time,subtrial$Sub_metering_1,xlab="",ylab="Energy sub metering")
with(subtrial,lines(Time,as.numeric(as.character(Sub_metering_1))))
with(subtrial,lines(Time,as.numeric(as.character(Sub_metering_2)),col="red"))
with(subtrial,lines(Time,as.numeric(as.character(Sub_metering_3)),col="blue"))
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
title(main="Energy sub-metering")
dev.copy(png,file="plot3.png")
