trial3<- read.table("household_power_consumption.txt",skip=1,sep=";")
names(trial3)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subtrial<-subset(trial3,trial3$Date=="1/2/2007"|trial3$Date=="2/2/2007")
subtrial$Date<-as.Date(subtrial$Date,format="%d/%m/%y")
subtrial$Time<-strptime(subtrial$Time,format="%H:%M:%S")
subtrial[1:1440,"Time"] <- format(subtrial[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subtrial[1441:2880,"Time"] <- format(subtrial[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(subtrial$Time,as.numeric(as.character(subtrial$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)") 
title(main="Global Active Power Vs Time")
dev.copy(png,file="plot2.png")