trial3<- read.table("household_power_consumption.txt",skip=1,sep=";")
names(trial3)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subtrial<-subset(trial3,trial3$Date=="1/2/2007"|trial3$Date=="2/2/2007")
hist(as.numeric(subtrial$Global_active_power),col="red",main="Global Active Power",xlab="Global Active Power (Kilowatts)")
dev.copy(png,file="plot1.png")